package nwwsio

// ProductInfo contains metadata about a weather product
type ProductInfo struct {
	Name     string
	Category string
}

// CommonProducts maps AWIPS product abbreviations to their metadata
// Source: https://forecast.weather.gov/product_types.php
var CommonProducts = map[string]ProductInfo{
	// Warnings
	"TOR": {Name: "Tornado Warning", Category: "Warning"},
	"SVR": {Name: "Severe Thunderstorm Warning", Category: "Warning"},
	"FFW": {Name: "Flash Flood Warning", Category: "Warning"},
	"FLW": {Name: "Flood Warning", Category: "Warning"},
	"CFW": {Name: "Coastal Flood Warning", Category: "Warning"},
	"WSW": {Name: "Winter Weather Warning", Category: "Warning"},
	"DSW": {Name: "Dust Storm Warning", Category: "Warning"},
	"EWW": {Name: "Extreme Wind Warning", Category: "Warning"},
	"FRW": {Name: "Fire Warning", Category: "Warning"},
	"HMW": {Name: "Hazardous Materials Warning", Category: "Warning"},
	"LEW": {Name: "Law Enforcement Warning", Category: "Warning"},
	"NUW": {Name: "Nuclear Power Plant Warning", Category: "Warning"},
	"RHW": {Name: "Radiological Hazard Warning", Category: "Warning"},
	"SPW": {Name: "Shelter in Place Warning", Category: "Warning"},
	"VOW": {Name: "Volcano Warning", Category: "Warning"},
	"EQW": {Name: "Earthquake Warning", Category: "Warning"},
	"CDW": {Name: "Civil Danger Warning", Category: "Warning"},
	"WAR": {Name: "Space Environment Warning", Category: "Warning"},
	"AVW": {Name: "Avalanche Warning", Category: "Warning"},
	"AWW": {Name: "Airport Weather Warning", Category: "Warning"},
	"SMW": {Name: "Special Marine Warning", Category: "Warning"},
	"SQW": {Name: "Snow Squall Warning", Category: "Warning"},

	// Watches
	"FFA": {Name: "Flash Flood Watch", Category: "Watch"},
	"AVA": {Name: "Avalanche Watch", Category: "Watch"},
	"SEL": {Name: "Severe Local Storm Watch", Category: "Watch"},
	"WOU": {Name: "Tornado/Severe Thunderstorm Watch", Category: "Watch"},
	"TSU": {Name: "Tsunami Watch/Warning", Category: "Watch"},
	"WAT": {Name: "Space Environment Watch", Category: "Watch"},

	// Advisories
	"AQA": {Name: "Air Quality Alert", Category: "Advisory"},
	"ASA": {Name: "Air Stagnation Advisory", Category: "Advisory"},
	"NPW": {Name: "Non-Precipitation Warnings/Watches/Advisories", Category: "Advisory"},
	"DSA": {Name: "Unnumbered Depression/Suspicious Area Advisory", Category: "Advisory"},

	// Statements
	"SVS": {Name: "Severe Weather Statement", Category: "Statement"},
	"SPS": {Name: "Special Weather Statement", Category: "Statement"},
	"FLS": {Name: "Flood Statement", Category: "Statement"},
	"FFS": {Name: "Flash Flood Statement", Category: "Statement"},
	"MWS": {Name: "Marine Weather Statement", Category: "Statement"},
	"RVI": {Name: "River Ice Statement", Category: "Statement"},
	"RVS": {Name: "River Statement", Category: "Statement"},
	"RNS": {Name: "Rain Information Statement", Category: "Statement"},
	"DGT": {Name: "Drought Information Statement", Category: "Statement"},
	"CWS": {Name: "Center Weather Statement", Category: "Statement"},
	"AQI": {Name: "Air Quality Index Statement", Category: "Statement"},
	"SDS": {Name: "Special Dispersion Statement", Category: "Statement"},

	// Forecasts
	"AFD": {Name: "Area Forecast Discussion", Category: "Forecast"},
	"ZFP": {Name: "Zone Forecast Product", Category: "Forecast"},
	"NOW": {Name: "Short Term Forecast", Category: "Forecast"},
	"PFM": {Name: "Point Forecast Matrices", Category: "Forecast"},
	"SFT": {Name: "Tabular State Forecast", Category: "Forecast"},
	"AFM": {Name: "Area Forecast Matrices", Category: "Forecast"},
	"AFP": {Name: "Area Forecast Product", Category: "Forecast"},
	"LFP": {Name: "Local Forecast", Category: "Forecast"},
	"SFP": {Name: "State Forecast", Category: "Forecast"},
	"OZF": {Name: "Zone Forecast", Category: "Forecast"},
	"TVL": {Name: "Travelers Forecast", Category: "Forecast"},
	"EFP": {Name: "3 To 5 Day Extended Forecast", Category: "Forecast"},
	"RDF": {Name: "Revised Digital Forecast", Category: "Forecast"},
	"QPF": {Name: "Quantitative Precipitation Forecast", Category: "Forecast"},
	"ESF": {Name: "Flood Potential Outlook", Category: "Forecast"},
	"RVF": {Name: "River Forecast", Category: "Forecast"},
	"RVD": {Name: "Daily River Forecasts", Category: "Forecast"},
	"ESG": {Name: "Extended Streamflow Guidance", Category: "Forecast"},
	"ESP": {Name: "Extended Streamflow Prediction", Category: "Forecast"},
	"ESS": {Name: "Water Supply Outlook", Category: "Forecast"},
	"PRE": {Name: "Preliminary Forecasts", Category: "Forecast"},
	"FTP": {Name: "FOUS Prog Max/Min Temp/Pop Guidance", Category: "Forecast"},

	// Aviation
	"TAF": {Name: "Terminal Aerodrome Forecast", Category: "Aviation"},
	"MTR": {Name: "METAR Formatted Surface Weather Observation", Category: "Aviation"},
	"AVG": {Name: "Aviation Gridded Forecast", Category: "Aviation"},
	"VFT": {Name: "Terminal Aerodrome Forecast Verification", Category: "Aviation"},
	"TAP": {Name: "Terminal Alerting Products", Category: "Aviation"},
	"TWB": {Name: "Transcribed Weather Broadcast", Category: "Aviation"},
	"FA0": {Name: "Aviation Area Forecast (Pacific)", Category: "Aviation"},
	"FA1": {Name: "Aviation Area Forecast (Northeast)", Category: "Aviation"},
	"FA2": {Name: "Aviation Area Forecast (Southeast)", Category: "Aviation"},
	"FA3": {Name: "Aviation Area Forecast (North Central)", Category: "Aviation"},
	"FA4": {Name: "Aviation Area Forecast (South Central)", Category: "Aviation"},
	"FA5": {Name: "Aviation Area Forecast (Rocky Mountains)", Category: "Aviation"},
	"FA6": {Name: "Aviation Area Forecast (West Coast)", Category: "Aviation"},
	"FA7": {Name: "Aviation Area Forecast (Juneau, AK)", Category: "Aviation"},
	"FA8": {Name: "Aviation Area Forecast (Anchorage, AK)", Category: "Aviation"},
	"FA9": {Name: "Aviation Area Forecast (Fairbanks, AK)", Category: "Aviation"},
	"OFA": {Name: "Offshore Aviation Area Forecast", Category: "Aviation"},
	"FD1": {Name: "6 Hour Winds Aloft Forecast", Category: "Aviation"},
	"FD2": {Name: "12 Hour Winds Aloft Forecast", Category: "Aviation"},
	"FD3": {Name: "24 Hour Winds Aloft Forecast", Category: "Aviation"},
	"SAW": {Name: "Prelim Notice of Watch & Cancellation (Aviation)", Category: "Aviation"},
	"TCA": {Name: "Aviation Tropical Cyclone Advisory", Category: "Aviation"},
	"WA1": {Name: "Airmet (Northeast)", Category: "Aviation"},
	"WA2": {Name: "Airmet (Southeast)", Category: "Aviation"},
	"WA3": {Name: "Airmet (North Central)", Category: "Aviation"},
	"WA4": {Name: "Airmet (South Central)", Category: "Aviation"},
	"WA5": {Name: "Airmet (Rocky Mountains)", Category: "Aviation"},
	"WA6": {Name: "Airmet (West Coast)", Category: "Aviation"},
	"WS1": {Name: "Sigmet (Northeast)", Category: "Aviation"},
	"WS2": {Name: "Sigmet (Southeast)", Category: "Aviation"},
	"WS3": {Name: "Sigmet (North Central)", Category: "Aviation"},
	"WS4": {Name: "Sigmet (South Central)", Category: "Aviation"},
	"WS5": {Name: "Sigmet (Rocky Mountains)", Category: "Aviation"},
	"WS6": {Name: "Sigmet (West Coast)", Category: "Aviation"},
	"SIG": {Name: "International Sigmet/Convective Sigmet", Category: "Aviation"},
	"WST": {Name: "Tropical Cyclone Sigmet", Category: "Aviation"},
	"WSV": {Name: "Volcanic Activity Sigmet", Category: "Aviation"},

	// Marine
	"OFF": {Name: "Offshore Forecast", Category: "Marine"},
	"CWF": {Name: "Coastal Waters Forecast", Category: "Marine"},
	"NSH": {Name: "Nearshore Marine Forecast", Category: "Marine"},
	"HSF": {Name: "High Seas Forecast", Category: "Marine"},
	"MWW": {Name: "Marine Weather Message", Category: "Marine"},
	"GLF": {Name: "Great Lakes Forecast", Category: "Marine"},
	"CPF": {Name: "Great Lakes Port Forecast", Category: "Marine"},
	"MFM": {Name: "Marine Forecast Matrix", Category: "Marine"},
	"MAW": {Name: "Amended Marine Forecast", Category: "Marine"},
	"SRF": {Name: "Surf Forecast", Category: "Marine"},
	"SRD": {Name: "Surf Discussion", Category: "Marine"},
	"MIM": {Name: "Marine Interpretation Message", Category: "Marine"},
	"MVF": {Name: "Marine Verification Coded Message", Category: "Marine"},
	"TCM": {Name: "Marine/Aviation Tropical Cyclone Advisory", Category: "Marine"},

	// Fire Weather
	"FWF": {Name: "Routine Fire Weather Forecast", Category: "Fire Weather"},
	"FWD": {Name: "Fire Weather Outlook Discussion", Category: "Fire Weather"},
	"FWS": {Name: "Spot Forecast", Category: "Fire Weather"},
	"FWL": {Name: "Land Management Forecasts", Category: "Fire Weather"},
	"FWM": {Name: "Miscellaneous Fire Weather Product", Category: "Fire Weather"},
	"FWN": {Name: "Fire Weather Notification", Category: "Fire Weather"},
	"FWO": {Name: "Fire Weather Observation", Category: "Fire Weather"},
	"RFW": {Name: "Red Flag Warning", Category: "Fire Weather"},
	"RFD": {Name: "Rangeland Fire Danger Forecast", Category: "Fire Weather"},
	"FWA": {Name: "Fire Weather Administrative Message", Category: "Fire Weather"},
	"AFW": {Name: "Fire Weather Matrix", Category: "Fire Weather"},
	"PFW": {Name: "Fire Weather Point Forecast Matrices", Category: "Fire Weather"},
	"SMF": {Name: "Smoke Management Weather Forecast", Category: "Fire Weather"},
	"FDI": {Name: "Fire Danger Indices", Category: "Fire Weather"},
	"SAG": {Name: "Snow Avalanche Guidance", Category: "Fire Weather"},

	// Hydrology
	"RRM": {Name: "Miscellaneous Hydrologic Data", Category: "Hydrology"},
	"RR1": {Name: "Hydro-Met Data Report Part 1", Category: "Hydrology"},
	"RR2": {Name: "Hydro-Met Data Report Part 2", Category: "Hydrology"},
	"RR3": {Name: "Hydro-Met Data Report Part 3", Category: "Hydrology"},
	"RR4": {Name: "Hydro-Met Data Report Part 4", Category: "Hydrology"},
	"RR5": {Name: "Hydro-Met Data Report Part 5", Category: "Hydrology"},
	"RR6": {Name: "Hydro-Met Data Report Part 6", Category: "Hydrology"},
	"RR7": {Name: "Hydro-Met Data Report Part 7", Category: "Hydrology"},
	"RR8": {Name: "Hydro-Met Data Report Part 8", Category: "Hydrology"},
	"RR9": {Name: "Hydro-Met Data Report Part 9", Category: "Hydrology"},
	"RRA": {Name: "Automated Hydrologic Observation", Category: "Hydrology"},
	"RRS": {Name: "HADS Data", Category: "Hydrology"},
	"HML": {Name: "AHPS XML", Category: "Hydrology"},
	"HMD": {Name: "Hydrometeorological Discussion", Category: "Hydrology"},
	"HYD": {Name: "Daily Hydrometeorological Products", Category: "Hydrology"},
	"HYM": {Name: "Monthly Hydrometeorological Product", Category: "Hydrology"},
	"FFG": {Name: "Flash Flood Guidance", Category: "Hydrology"},
	"FFH": {Name: "Headwater Guidance", Category: "Hydrology"},
	"FLN": {Name: "National Flood Summary", Category: "Hydrology"},
	"QPS": {Name: "Quantitative Precipitation Statement", Category: "Hydrology"},
	"RVA": {Name: "River Summary", Category: "Hydrology"},
	"RVM": {Name: "Miscellaneous River Product", Category: "Hydrology"},
	"RVR": {Name: "River Recreation Statement", Category: "Hydrology"},
	"LKE": {Name: "Lake Stages", Category: "Hydrology"},
	"MAP": {Name: "Mean Areal Precipitation", Category: "Hydrology"},

	// Climate
	"CLI": {Name: "Climatological Report (Daily)", Category: "Climate"},
	"CLM": {Name: "Climatological Report (Monthly)", Category: "Climate"},
	"CLA": {Name: "Climatological Report (Annual)", Category: "Climate"},
	"CLQ": {Name: "Climatological Report (Quarterly)", Category: "Climate"},
	"CLS": {Name: "Climatological Report (Seasonal)", Category: "Climate"},
	"CLT": {Name: "Climate Report", Category: "Climate"},
	"CF6": {Name: "WFO Monthly/Daily Climate Data", Category: "Climate"},
	"RTP": {Name: "Regional Max/Min Temp and Precipitation", Category: "Climate"},
	"RER": {Name: "Record Event Report", Category: "Climate"},
	"REC": {Name: "Recreational Report", Category: "Climate"},
	"LCD": {Name: "Preliminary Local Climatological Data", Category: "Climate"},
	"SCD": {Name: "Supplementary Climatological Data", Category: "Climate"},
	"CMM": {Name: "Coded Climatological Monthly Means", Category: "Climate"},
	"STP": {Name: "State Max/Min Temperature and Precipitation", Category: "Climate"},
	"TPT": {Name: "Temperature Precipitation Table", Category: "Climate"},
	"SCN": {Name: "Soil Climate Analysis Network Data", Category: "Climate"},
	"WCR": {Name: "Weekly Weather and Crop Report", Category: "Climate"},
	"WDA": {Name: "Weekly Data for Agriculture", Category: "Climate"},

	// Observations
	"LSR": {Name: "Local Storm Report", Category: "Observation"},
	"BOY": {Name: "Buoy Report", Category: "Observation"},
	"BRG": {Name: "Coast Guard Observations", Category: "Observation"},
	"SHP": {Name: "Surface Ship Report at Synoptic Time", Category: "Observation"},
	"SSM": {Name: "Main Synoptic Hour Surface Observation", Category: "Observation"},
	"LCO": {Name: "Local Cooperative Observation", Category: "Observation"},
	"AGO": {Name: "Agricultural Observations", Category: "Observation"},
	"RFI": {Name: "RFI Observation", Category: "Observation"},
	"IOB": {Name: "Ice Observation", Category: "Observation"},
	"SDO": {Name: "Supplementary Data Observation (ASOS)", Category: "Observation"},
	"DSM": {Name: "ASOS Daily Summary", Category: "Observation"},
	"MSM": {Name: "ASOS Monthly Summary Message", Category: "Observation"},
	"CGR": {Name: "Coast Guard Surface Report", Category: "Observation"},
	"PLS": {Name: "Plain Language Ship Report", Category: "Observation"},
	"TID": {Name: "Tide Report", Category: "Observation"},
	"ICE": {Name: "Ice Forecast", Category: "Observation"},
	"MAN": {Name: "Rawinsonde Observation Mandatory Levels", Category: "Observation"},
	"SGL": {Name: "Rawinsonde Observation Significant Levels", Category: "Observation"},
	"ABV": {Name: "Rawinsonde Data Above 100 Millibars", Category: "Observation"},
	"MOB": {Name: "MOB Observations", Category: "Observation"},

	// Tropical
	"TCP": {Name: "Public Tropical Cyclone Advisory", Category: "Tropical"},
	"TCD": {Name: "Tropical Cyclone Discussion", Category: "Tropical"},
	"TCE": {Name: "Tropical Cyclone Position Estimate", Category: "Tropical"},
	"TCS": {Name: "Satellite Tropical Cyclone Summary", Category: "Tropical"},
	"TCU": {Name: "Tropical Cyclone Update", Category: "Tropical"},
	"TCV": {Name: "Tropical Cyclone Watch/Warning Break Points", Category: "Tropical"},
	"TWD": {Name: "Tropical Weather Discussion", Category: "Tropical"},
	"TWO": {Name: "Tropical Weather Outlook and Summary", Category: "Tropical"},
	"TWS": {Name: "Tropical Weather Summary", Category: "Tropical"},
	"HLS": {Name: "Hurricane Local Statement", Category: "Tropical"},
	"PSH": {Name: "Post Storm Hurricane Report", Category: "Tropical"},
	"PWS": {Name: "Tropical Cyclone Probabilities", Category: "Tropical"},
	"CHG": {Name: "Computer Hurricane Guidance", Category: "Tropical"},
	"SPF": {Name: "Storm Strike Probability Bulletin", Category: "Tropical"},
	"STD": {Name: "Satellite Tropical Disturbance Summary", Category: "Tropical"},

	// Space Weather
	"ADV": {Name: "Generic Space Environment Advisory", Category: "Space Weather"},
	"ALT": {Name: "Space Environment Alert", Category: "Space Weather"},
	"SUM": {Name: "Space Weather Message", Category: "Space Weather"},
	"CUR": {Name: "Routine Space Environment Products", Category: "Space Weather"},
	"DAY": {Name: "Routine Space Environment Product (Daily)", Category: "Space Weather"},
	"WEK": {Name: "Routine Space Environment Product (Weekly)", Category: "Space Weather"},
	"MON": {Name: "Routine Space Environment Product (Monthly)", Category: "Space Weather"},

	// Public Info
	"PNS": {Name: "Public Information Statement", Category: "Public Info"},
	"HWO": {Name: "Hazardous Weather Outlook", Category: "Public Info"},
	"AWO": {Name: "Area Weather Outlook", Category: "Public Info"},
	"PWO": {Name: "Public Severe Weather Outlook", Category: "Public Info"},
	"NWR": {Name: "NOAA Weather Radio Forecast", Category: "Public Info"},
	"VAA": {Name: "Volcanic Activity Advisory", Category: "Public Info"},

	// Summaries
	"RWR": {Name: "Regional Weather Roundup", Category: "Summary"},
	"RWS": {Name: "Regional Weather Summary", Category: "Summary"},
	"AWS": {Name: "Area Weather Summary", Category: "Summary"},
	"SWS": {Name: "State Weather Summary", Category: "Summary"},
	"SYN": {Name: "Regional Weather Synopsis", Category: "Summary"},
	"WWA": {Name: "Watch Status Report", Category: "Summary"},
	"SCS": {Name: "Selected Cities Summary", Category: "Summary"},
	"GLS": {Name: "Great Lakes Storm Summary", Category: "Summary"},
	"SCC": {Name: "Storm Summary", Category: "Summary"},
	"HRR": {Name: "Weather Roundup", Category: "Summary"},
	"HWR": {Name: "Hourly Weather Roundup", Category: "Summary"},
	"BRT": {Name: "Hourly Roundup for Weather Radio", Category: "Summary"},

	// Administrative
	"CAP": {Name: "Common Alerting Protocol", Category: "Administrative"},
	"ADM": {Name: "Alert Administrative Message", Category: "Administrative"},
	"ADA": {Name: "Alarm/Alert Administrative Msg", Category: "Administrative"},
	"ADR": {Name: "NWS Administrative Message", Category: "Administrative"},
	"FTM": {Name: "WSR-88D Radar Outage Notification", Category: "Administrative"},
	"FSH": {Name: "Natl Marine Fisheries Administrative Message", Category: "Administrative"},
	"WCN": {Name: "Weather Watch Clearance Notification", Category: "Administrative"},
	"WDU": {Name: "Warning Decision Update", Category: "Administrative"},
	"CWA": {Name: "Center (CWSU) Weather Advisory", Category: "Administrative"},
	"MIS": {Name: "Miscellaneous Local Product", Category: "Administrative"},
	"INI": {Name: "ADMINISTR [NOUS51 KWBC]", Category: "Administrative"},

	// Outlook
	"SWO": {Name: "Severe Storm Outlook Narrative", Category: "Outlook"},
	"CFP": {Name: "Convective Forecast Product", Category: "Outlook"},
	"DDO": {Name: "Daily Dispersion Outlook", Category: "Outlook"},
	"EOL": {Name: "Average 6 To 10 Day Weather Outlook", Category: "Outlook"},
	"POE": {Name: "Probability of Exceed", Category: "Outlook"},
	"PTS": {Name: "Probabilistic Outlook Points", Category: "Outlook"},
	"WWP": {Name: "Severe Thunderstorm/Tornado Watch Probabilities", Category: "Outlook"},
	"AWU": {Name: "Area Weather Update", Category: "Outlook"},

	// Satellite
	"SAT": {Name: "APT Prediction", Category: "Satellite"},
	"SCP": {Name: "Satellite Cloud Product", Category: "Satellite"},
	"SIM": {Name: "Satellite Interpretation Message", Category: "Satellite"},
	"SPE": {Name: "Satellite Precipitation Estimates", Category: "Satellite"},
	"OSW": {Name: "Ocean Surface Winds", Category: "Satellite"},
	"IDM": {Name: "Ice Drift Vectors", Category: "Satellite"},
	"LTG": {Name: "Lightning Data", Category: "Satellite"},

	// Data
	"COD": {Name: "Coded Analysis and Forecasts", Category: "Data"},
	"CCF": {Name: "Coded City Forecast", Category: "Data"},
	"FZL": {Name: "Freezing Level Data", Category: "Data"},
	"RSD": {Name: "Daily Snotel Data", Category: "Data"},
	"RSM": {Name: "Monthly Snotel Data", Category: "Data"},
	"RRY": {Name: "ASOS SHEF Hourly Routine Test", Category: "Data"},
	"LLS": {Name: "Low-Level Sounding", Category: "Data"},

	// Test/Emergency
	"DMO": {Name: "Practice/Demo Warning", Category: "Test"},
	"RMT": {Name: "Required Monthly Test", Category: "Test"},
	"RWT": {Name: "Required Weekly Test", Category: "Test"},
	"MTT": {Name: "METAR Test Message", Category: "Test"},
	"CEM": {Name: "Civil Emergency Message", Category: "Emergency"},
	"LAE": {Name: "Local Area Emergency", Category: "Emergency"},
	"CAE": {Name: "Child Abduction Emergency", Category: "Emergency"},
	"EVI": {Name: "Evacuation Immediate", Category: "Emergency"},
	"TOE": {Name: "911 Telephone Outage Emergency", Category: "Emergency"},
	"TIB": {Name: "Tsunami Bulletin", Category: "Emergency"},
	"TMA": {Name: "Tsunami Tide/Seismic Message Ack", Category: "Emergency"},
	"EQI": {Name: "Tsunami Bulletin", Category: "Emergency"},
	"EQR": {Name: "Earthquake Report", Category: "Emergency"},

	// Miscellaneous
	"AGF": {Name: "Agricultural Forecast", Category: "Agriculture"},
	"SAB": {Name: "Special Avalanche Bulletin", Category: "Avalanche"},
	"SAF": {Name: "Special Agricultural Forecast", Category: "Agriculture"},
	"TAV": {Name: "Travelers Forecast Table", Category: "Travel"},
	"UVI": {Name: "Ultraviolet Index", Category: "Health"},
	"PRB": {Name: "Heat Index Forecast Tables", Category: "Health"},
	"STO": {Name: "Road Condition Reports", Category: "Travel"},
	"STQ": {Name: "Spot Forecast Request", Category: "Request"},
	"URN": {Name: "Aircraft Reconnaissance", Category: "Recon"},
	"NOU": {Name: "Weather Reconnaissance Flights", Category: "Recon"},
	"SRG": {Name: "Soaring Guidance", Category: "Aviation"},
	"VER": {Name: "Forecast Verification Statistics", Category: "Verification"},
	"SEV": {Name: "SPC Watch Point Information", Category: "Watch"},
	"STA": {Name: "Network and Severe Weather Statistical Summaries", Category: "Statistics"},
	"KPA": {Name: "Keep Alive Message", Category: "Administrative"},
	"OMR": {Name: "Other Marine Products", Category: "Marine"},
	"OPU": {Name: "Other Public Products", Category: "Public Info"},
	"OAV": {Name: "Other Aviation Products", Category: "Aviation"},
	"OBS": {Name: "Observations", Category: "Observation"},
	"FOP": {Name: "Flood Potential Outlook", Category: "Forecast"},
	"LOW": {Name: "Low Temperatures", Category: "Forecast"},
	"TUV": {Name: "Weather Bulletin", Category: "Public Info"},
	"RET": {Name: "EAS Activation Request", Category: "Administrative"},
	"PMD": {Name: "Prognostic Meteorological Discussion", Category: "Discussion"},
	"SOO": {Name: "SOO Product", Category: "Administrative"},
	"SLS": {Name: "Severe Local Storm Watch", Category: "Watch"},
	"BLU": {Name: "Blue Alert", Category: "Alert"},
	"GRE": {Name: "GREEN", Category: "Alert"},
	"RFR": {Name: "Route Forecast", Category: "Forecast"},
	"MRP": {Name: "Techniques Development Laboratory Marine Product", Category: "Marine"},
	"OUA": {Name: "Other Upper Air Data", Category: "Observation"},
	"OSO": {Name: "Other Surface Observations", Category: "Observation"},
	"PRC": {Name: "State Pilot Report Collective", Category: "Aviation"},
	"NOX": {Name: "Data Mgt Message", Category: "Data"},
	"FOF": {Name: "Upper Wind Fallout Forecast", Category: "Forecast"},
}
